# Generated by Django 5.0.6 on 2024-06-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_created_by_alter_post_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='angry',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='dislike',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='like',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='loved',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='ok',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
