# Generated by Django 5.0.6 on 2024-06-23 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='website_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
