# Generated by Django 5.0.6 on 2024-06-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_website_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follower',
            options={'verbose_name_plural': 'followers'},
        ),
    ]
